"""session_story_nullable

Revision ID: 220c929fb869
Revises: e3012a834948
Create Date: 2026-07-23 06:59:45.086093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220c929fb869'
down_revision: Union[str, None] = 'e3012a834948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'story_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('story_character_snapshots', 'story_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('story_character_snapshots', 'story_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sessions', 'story_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
